[package]
name = "web_splats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17"
winit = "0.28.1"
cgmath = { version = "0.18.0", features = [
    "bytemuck",
], git = 'https://github.com/rustgd/cgmath' }
pollster = "0.3.0"
env_logger = "0.10"
structopt = "0.3.26"
bytemuck = { version = "1.13.0", features = ["derive"] }
anyhow = "1.0.70"
ply-rs = "0.1.3"
byteorder = "1.4.3"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
rand = "0.8.5"
futures-intrusive = "0.5"

[lib]
path = "src/lib.rs"

[[bin]]
name = "viewer"

[[bin]]
name = "sort_test"
