[package]
name = "web_splats"
version = "0.1.0"
edition = "2021"
authors = ["Simon Niedermayr", "Josef Stumpfegger"]
description = "3D Gaussian Splatting Viewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.19.1" }
winit = "0.29.10"
cgmath = { version = "0.18.0", features = [
    "bytemuck",
], git = 'https://github.com/rustgd/cgmath' }
env_logger = "0.11"
clap = { version = "4.4.6", features = ["derive"] }
bytemuck = { version = "1.13.0", features = ["derive"] }
anyhow = "1.0.70"
ply-rs = "0.1.3"
byteorder = "1.4.3"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
rand = "0.8.5"
num-traits = "0.2.16"
half = { version = "2.3.1", features = ["bytemuck", "num-traits"] }
log = "0.4.20"
rayon = "1.8.0"
image = "0.24.6"
indicatif = "0.17.7"


egui = "0.26.1"
egui-wgpu = "0.26.1"
egui-winit = { version = "0.26.1", features = [], default-features = false }
egui_plot = "0.26.1"
egui_dnd = "0.7.0"

npyz = { version = "0.8.3", features = ["npz", "half"], optional = true }
futures-intrusive = "0.5.0"
splines = { version = "4.3.1", features = [
    "cgmath",
], git = "https://github.com/KeKsBoTer/splines" }

imageproc = { version = "0.23.0", optional = true }
minimp4 = { version = "0.2.0", optional = true, git = "https://github.com/darkskygit/minimp4.rs.git", branch = "master" }
openh264 = { version = "0.5.0", optional = true }

[dev-dependencies]
wasm-bindgen-cli = "0.2.90"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "viewer"

[[bin]]
name = "video"
required-features = ["video"]

[features]
npz = ["dep:npyz"]
video = ["dep:minimp4", "dep:openh264", "dep:imageproc"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = { version = "0.3.0", features = ["macro"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]

getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.84"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.37"
console_log = "1"
log = "0.4"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
web-sys = { version = "0.3.64" }

[profile.web-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
