[package]
name = "web_splats"
version = "0.1.0"
edition = "2021"
authors = ["Simon Niedermayr", "Josef Stumpfegger"]
description = "3D Gaussian Splatting Viewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17"
winit = "0.28.1"
cgmath = { version = "0.18.0", features = [
    "bytemuck",
], git = 'https://github.com/rustgd/cgmath' }
env_logger = "0.10"
clap = { version = "4.4.6", features = ["derive"] }
bytemuck = { version = "1.13.0", features = ["derive"] }
anyhow = "1.0.70"
ply-rs = "0.1.3"
byteorder = "1.4.3"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
rand = "0.8.5"
num-traits = "0.2.16"
half = { version = "2.3.1", features = ["bytemuck", "num-traits"] }
log = "0.4.20"
rayon = "1.8.0"
image = "0.24.6"
indicatif = "0.17.7"

egui = "0.23.0"
egui-wgpu = "0.23.0"
egui-winit = { version = "0.23.0", features = [], default-features = false }
egui_plot = "0.23.0"

npyz = { version = "0.8", features = ["npz"], optional = true }
futures-intrusive = "0.5.0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "viewer"

[[bin]]
name = "render"

[[bin]]
name = "measure"


[features]
npz = ["dep:npyz"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = { version = "0.3.0", features = ["macro"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]

getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.84"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.37"
console_log = "1"
log = "0.4"
instant = "0.1.12"
web-sys = { version = "0.3.64", features = [
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
    'Element',
] }
